### ISSUE TITLE
Conjugate test failing

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/rita-script#1]
there was a return; on line 79 so the test below was not running.

now fail on this case

    args = {
      number: RiTa.PLURAL,
      person: RiTa.SECOND_PERSON,
      tense: RiTa.PAST_TENSE
    };
    equal(RiTa.conjugate("barter", args), "bartered");
    equal(RiTa.conjugate("run", args), "ran");

    s = ["compete", "complete", "eject"];
    a = ["competed", "completed", "ejected"];
    ok(a.length === s.length);
    for (let i = 0; i < s.length; i++) {
      c = RiTa.conjugate(s[i], args);
      equal(c, a[i]);
    }

**Comment by dhowe** [comment]
see issues/known-issues.js
