### ISSUE TITLE
Add progress bar for loading of workbench files

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita-script#7]
path: /web/workbench/index.html

when 'load' is clicked, a progress bar should be displayed 

the file below shows the problem (click load, then navigate to it in finder):
[warpeace_input.txt](https://github.com/dhowe/rita-script/files/3965532/warpeace_input.txt)

**Comment by kennyviperhk** [comment]
Checked with multiple sources with FileReader, it can't really show the number of bytes loaded. The staus only show after the file is loaded. I use a gif to indicate it is loading in progress for now. Do you think it is alright?

**Comment by dhowe** [comment]
Good for now
